/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.unipampa.lesse.ui.AbstractCanopusUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CanopusUiModule extends AbstractCanopusUiModule {
  public CanopusUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
