/*
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.unipampa.lesse.parser.antlr.internal.InternalCanopusParser;
import org.unipampa.lesse.services.CanopusGrammarAccess;

public class CanopusParser extends AbstractAntlrParser {

	@Inject
	private CanopusGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCanopusParser createParser(XtextTokenStream stream) {
		return new InternalCanopusParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CanopusGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CanopusGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
