/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.ui.contentassist;

import org.unipampa.lesse.ui.contentassist.AbstractCanopusProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CanopusProposalProvider extends AbstractCanopusProposalProvider {
}
