/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.ide;

import org.unipampa.lesse.ide.AbstractCanopusIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CanopusIdeModule extends AbstractCanopusIdeModule {
}
