/*
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.unipampa.lesse.xcanopus.ui.internal.XcanopusActivator;

public class CanopusUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XcanopusActivator.getInstance().getInjector("org.unipampa.lesse.Canopus");
	}

}
