/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.unipampa.lesse.canopus.CanopusFactory
 * @model kind="package"
 * @generated
 */
public interface CanopusPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "canopus";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unipampa.org/lesse/Canopus";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "canopus";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CanopusPackage eINSTANCE = org.unipampa.lesse.canopus.impl.CanopusPackageImpl.init();

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.ModelImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Includes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INCLUDES = 0;

  /**
   * The feature id for the '<em><b>Monitorings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MONITORINGS = 1;

  /**
   * The feature id for the '<em><b>Suts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SUTS = 2;

  /**
   * The feature id for the '<em><b>Load Generators</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__LOAD_GENERATORS = 3;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.IncludeImpl <em>Include</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.IncludeImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getInclude()
   * @generated
   */
  int INCLUDE = 1;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__IMPORT_URI = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE__NAME = 1;

  /**
   * The number of structural features of the '<em>Include</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCLUDE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.MonitoringImpl <em>Monitoring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.MonitoringImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMonitoring()
   * @generated
   */
  int MONITORING = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING__NAME = 0;

  /**
   * The feature id for the '<em><b>Project Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING__PROJECT_LABEL = 1;

  /**
   * The feature id for the '<em><b>Project Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING__PROJECT_AUTHOR = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING__DESCRIPTION = 3;

  /**
   * The feature id for the '<em><b>Suts</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING__SUTS = 4;

  /**
   * The feature id for the '<em><b>Load Generators</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING__LOAD_GENERATORS = 5;

  /**
   * The number of structural features of the '<em>Monitoring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITORING_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.MetricImpl <em>Metric</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.MetricImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMetric()
   * @generated
   */
  int METRIC = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC__THRESHOLD = 1;

  /**
   * The number of structural features of the '<em>Metric</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.SUTImpl <em>SUT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.SUTImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getSUT()
   * @generated
   */
  int SUT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT__NAME = 0;

  /**
   * The feature id for the '<em><b>Hostname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT__HOSTNAME = 1;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT__IP = 2;

  /**
   * The feature id for the '<em><b>Hardware</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT__HARDWARE = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT__TYPE = 4;

  /**
   * The number of structural features of the '<em>SUT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.LoadGeneratorImpl <em>Load Generator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.LoadGeneratorImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getLoadGenerator()
   * @generated
   */
  int LOAD_GENERATOR = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_GENERATOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Hostname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_GENERATOR__HOSTNAME = 1;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_GENERATOR__IP = 2;

  /**
   * The feature id for the '<em><b>Hardware</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_GENERATOR__HARDWARE = 3;

  /**
   * The number of structural features of the '<em>Load Generator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_GENERATOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.MonitorImpl <em>Monitor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.MonitorImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMonitor()
   * @generated
   */
  int MONITOR = 6;

  /**
   * The feature id for the '<em><b>Hostname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR__HOSTNAME = 0;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR__IP = 1;

  /**
   * The feature id for the '<em><b>Hardware</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR__HARDWARE = 2;

  /**
   * The feature id for the '<em><b>Sut</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR__SUT = 3;

  /**
   * The number of structural features of the '<em>Monitor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONITOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.MetricModelImpl <em>Metric Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.MetricModelImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMetricModel()
   * @generated
   */
  int METRIC_MODEL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Metricmodel</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_MODEL__METRICMODEL = 1;

  /**
   * The number of structural features of the '<em>Metric Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.MetricCollectionImpl <em>Metric Collection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.MetricCollectionImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMetricCollection()
   * @generated
   */
  int METRIC_COLLECTION = 8;

  /**
   * The feature id for the '<em><b>Metric</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_COLLECTION__METRIC = 0;

  /**
   * The number of structural features of the '<em>Metric Collection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_COLLECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.ThresholdImpl <em>Threshold</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.ThresholdImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getThreshold()
   * @generated
   */
  int THRESHOLD = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD__VALUE = 0;

  /**
   * The number of structural features of the '<em>Threshold</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int THRESHOLD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.MemoryImpl <em>Memory</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.MemoryImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMemory()
   * @generated
   */
  int MEMORY = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY__NAME = METRIC__NAME;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY__THRESHOLD = METRIC__THRESHOLD;

  /**
   * The number of structural features of the '<em>Memory</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY_FEATURE_COUNT = METRIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.DiskImpl <em>Disk</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.DiskImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getDisk()
   * @generated
   */
  int DISK = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK__NAME = METRIC__NAME;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK__THRESHOLD = METRIC__THRESHOLD;

  /**
   * The feature id for the '<em><b>Disk io counter</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK__DISK_IO_COUNTER = METRIC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Disk</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_FEATURE_COUNT = METRIC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.TransactionImpl <em>Transaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.TransactionImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getTransaction()
   * @generated
   */
  int TRANSACTION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__NAME = METRIC__NAME;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__THRESHOLD = METRIC__THRESHOLD;

  /**
   * The number of structural features of the '<em>Transaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION_FEATURE_COUNT = METRIC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.Disk_IO_CounterImpl <em>Disk IO Counter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.Disk_IO_CounterImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getDisk_IO_Counter()
   * @generated
   */
  int DISK_IO_COUNTER = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_IO_COUNTER__NAME = 0;

  /**
   * The feature id for the '<em><b>Counter Disk</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_IO_COUNTER__COUNTER_DISK = 1;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_IO_COUNTER__THRESHOLD = 2;

  /**
   * The feature id for the '<em><b>Criteria</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_IO_COUNTER__CRITERIA = 3;

  /**
   * The number of structural features of the '<em>Disk IO Counter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISK_IO_COUNTER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.impl.CriteriaImpl <em>Criteria</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.impl.CriteriaImpl
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getCriteria()
   * @generated
   */
  int CRITERIA = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRITERIA__VALUE = 0;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRITERIA__THRESHOLD = 1;

  /**
   * The number of structural features of the '<em>Criteria</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CRITERIA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.Hardware <em>Hardware</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.Hardware
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getHardware()
   * @generated
   */
  int HARDWARE = 15;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.SUTType <em>SUT Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.SUTType
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getSUTType()
   * @generated
   */
  int SUT_TYPE = 16;

  /**
   * The meta object id for the '{@link org.unipampa.lesse.canopus.COUNTER_DISK <em>COUNTER DISK</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.unipampa.lesse.canopus.COUNTER_DISK
   * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getCOUNTER_DISK()
   * @generated
   */
  int COUNTER_DISK = 17;


  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.unipampa.lesse.canopus.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.canopus.Model#getIncludes <em>Includes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Includes</em>'.
   * @see org.unipampa.lesse.canopus.Model#getIncludes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Includes();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.canopus.Model#getMonitorings <em>Monitorings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Monitorings</em>'.
   * @see org.unipampa.lesse.canopus.Model#getMonitorings()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Monitorings();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.canopus.Model#getSuts <em>Suts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Suts</em>'.
   * @see org.unipampa.lesse.canopus.Model#getSuts()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Suts();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.canopus.Model#getLoadGenerators <em>Load Generators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Load Generators</em>'.
   * @see org.unipampa.lesse.canopus.Model#getLoadGenerators()
   * @see #getModel()
   * @generated
   */
  EReference getModel_LoadGenerators();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Include <em>Include</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Include</em>'.
   * @see org.unipampa.lesse.canopus.Include
   * @generated
   */
  EClass getInclude();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Include#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see org.unipampa.lesse.canopus.Include#getImportURI()
   * @see #getInclude()
   * @generated
   */
  EAttribute getInclude_ImportURI();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Include#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.Include#getName()
   * @see #getInclude()
   * @generated
   */
  EAttribute getInclude_Name();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Monitoring <em>Monitoring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Monitoring</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring
   * @generated
   */
  EClass getMonitoring();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitoring#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring#getName()
   * @see #getMonitoring()
   * @generated
   */
  EAttribute getMonitoring_Name();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitoring#getProjectLabel <em>Project Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Project Label</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring#getProjectLabel()
   * @see #getMonitoring()
   * @generated
   */
  EAttribute getMonitoring_ProjectLabel();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitoring#getProjectAuthor <em>Project Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Project Author</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring#getProjectAuthor()
   * @see #getMonitoring()
   * @generated
   */
  EAttribute getMonitoring_ProjectAuthor();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitoring#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring#getDescription()
   * @see #getMonitoring()
   * @generated
   */
  EAttribute getMonitoring_Description();

  /**
   * Returns the meta object for the reference list '{@link org.unipampa.lesse.canopus.Monitoring#getSuts <em>Suts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Suts</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring#getSuts()
   * @see #getMonitoring()
   * @generated
   */
  EReference getMonitoring_Suts();

  /**
   * Returns the meta object for the reference list '{@link org.unipampa.lesse.canopus.Monitoring#getLoadGenerators <em>Load Generators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Load Generators</em>'.
   * @see org.unipampa.lesse.canopus.Monitoring#getLoadGenerators()
   * @see #getMonitoring()
   * @generated
   */
  EReference getMonitoring_LoadGenerators();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Metric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric</em>'.
   * @see org.unipampa.lesse.canopus.Metric
   * @generated
   */
  EClass getMetric();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Metric#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.Metric#getName()
   * @see #getMetric()
   * @generated
   */
  EAttribute getMetric_Name();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.canopus.Metric#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Threshold</em>'.
   * @see org.unipampa.lesse.canopus.Metric#getThreshold()
   * @see #getMetric()
   * @generated
   */
  EReference getMetric_Threshold();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.SUT <em>SUT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SUT</em>'.
   * @see org.unipampa.lesse.canopus.SUT
   * @generated
   */
  EClass getSUT();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.SUT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.SUT#getName()
   * @see #getSUT()
   * @generated
   */
  EAttribute getSUT_Name();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.SUT#getHostname <em>Hostname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hostname</em>'.
   * @see org.unipampa.lesse.canopus.SUT#getHostname()
   * @see #getSUT()
   * @generated
   */
  EAttribute getSUT_Hostname();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.SUT#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip</em>'.
   * @see org.unipampa.lesse.canopus.SUT#getIp()
   * @see #getSUT()
   * @generated
   */
  EAttribute getSUT_Ip();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.SUT#getHardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hardware</em>'.
   * @see org.unipampa.lesse.canopus.SUT#getHardware()
   * @see #getSUT()
   * @generated
   */
  EAttribute getSUT_Hardware();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.SUT#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.unipampa.lesse.canopus.SUT#getType()
   * @see #getSUT()
   * @generated
   */
  EAttribute getSUT_Type();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.LoadGenerator <em>Load Generator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load Generator</em>'.
   * @see org.unipampa.lesse.canopus.LoadGenerator
   * @generated
   */
  EClass getLoadGenerator();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.LoadGenerator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.LoadGenerator#getName()
   * @see #getLoadGenerator()
   * @generated
   */
  EAttribute getLoadGenerator_Name();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.LoadGenerator#getHostname <em>Hostname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hostname</em>'.
   * @see org.unipampa.lesse.canopus.LoadGenerator#getHostname()
   * @see #getLoadGenerator()
   * @generated
   */
  EAttribute getLoadGenerator_Hostname();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.LoadGenerator#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip</em>'.
   * @see org.unipampa.lesse.canopus.LoadGenerator#getIp()
   * @see #getLoadGenerator()
   * @generated
   */
  EAttribute getLoadGenerator_Ip();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.LoadGenerator#getHardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hardware</em>'.
   * @see org.unipampa.lesse.canopus.LoadGenerator#getHardware()
   * @see #getLoadGenerator()
   * @generated
   */
  EAttribute getLoadGenerator_Hardware();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Monitor <em>Monitor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Monitor</em>'.
   * @see org.unipampa.lesse.canopus.Monitor
   * @generated
   */
  EClass getMonitor();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitor#getHostname <em>Hostname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hostname</em>'.
   * @see org.unipampa.lesse.canopus.Monitor#getHostname()
   * @see #getMonitor()
   * @generated
   */
  EAttribute getMonitor_Hostname();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitor#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip</em>'.
   * @see org.unipampa.lesse.canopus.Monitor#getIp()
   * @see #getMonitor()
   * @generated
   */
  EAttribute getMonitor_Ip();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Monitor#getHardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hardware</em>'.
   * @see org.unipampa.lesse.canopus.Monitor#getHardware()
   * @see #getMonitor()
   * @generated
   */
  EAttribute getMonitor_Hardware();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.canopus.Monitor#getSut <em>Sut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sut</em>'.
   * @see org.unipampa.lesse.canopus.Monitor#getSut()
   * @see #getMonitor()
   * @generated
   */
  EReference getMonitor_Sut();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.MetricModel <em>Metric Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric Model</em>'.
   * @see org.unipampa.lesse.canopus.MetricModel
   * @generated
   */
  EClass getMetricModel();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.MetricModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.MetricModel#getName()
   * @see #getMetricModel()
   * @generated
   */
  EAttribute getMetricModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.canopus.MetricModel#getMetricmodel <em>Metricmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metricmodel</em>'.
   * @see org.unipampa.lesse.canopus.MetricModel#getMetricmodel()
   * @see #getMetricModel()
   * @generated
   */
  EReference getMetricModel_Metricmodel();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.MetricCollection <em>Metric Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric Collection</em>'.
   * @see org.unipampa.lesse.canopus.MetricCollection
   * @generated
   */
  EClass getMetricCollection();

  /**
   * Returns the meta object for the containment reference list '{@link org.unipampa.lesse.canopus.MetricCollection#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Metric</em>'.
   * @see org.unipampa.lesse.canopus.MetricCollection#getMetric()
   * @see #getMetricCollection()
   * @generated
   */
  EReference getMetricCollection_Metric();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Threshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Threshold</em>'.
   * @see org.unipampa.lesse.canopus.Threshold
   * @generated
   */
  EClass getThreshold();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Threshold#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.unipampa.lesse.canopus.Threshold#getValue()
   * @see #getThreshold()
   * @generated
   */
  EAttribute getThreshold_Value();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Memory <em>Memory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Memory</em>'.
   * @see org.unipampa.lesse.canopus.Memory
   * @generated
   */
  EClass getMemory();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Disk <em>Disk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Disk</em>'.
   * @see org.unipampa.lesse.canopus.Disk
   * @generated
   */
  EClass getDisk();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.canopus.Disk#getDisk_io_counter <em>Disk io counter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Disk io counter</em>'.
   * @see org.unipampa.lesse.canopus.Disk#getDisk_io_counter()
   * @see #getDisk()
   * @generated
   */
  EReference getDisk_Disk_io_counter();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Transaction <em>Transaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transaction</em>'.
   * @see org.unipampa.lesse.canopus.Transaction
   * @generated
   */
  EClass getTransaction();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Disk_IO_Counter <em>Disk IO Counter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Disk IO Counter</em>'.
   * @see org.unipampa.lesse.canopus.Disk_IO_Counter
   * @generated
   */
  EClass getDisk_IO_Counter();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.unipampa.lesse.canopus.Disk_IO_Counter#getName()
   * @see #getDisk_IO_Counter()
   * @generated
   */
  EAttribute getDisk_IO_Counter_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getCounterDisk <em>Counter Disk</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Counter Disk</em>'.
   * @see org.unipampa.lesse.canopus.Disk_IO_Counter#getCounterDisk()
   * @see #getDisk_IO_Counter()
   * @generated
   */
  EAttribute getDisk_IO_Counter_CounterDisk();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Threshold</em>'.
   * @see org.unipampa.lesse.canopus.Disk_IO_Counter#getThreshold()
   * @see #getDisk_IO_Counter()
   * @generated
   */
  EReference getDisk_IO_Counter_Threshold();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getCriteria <em>Criteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Criteria</em>'.
   * @see org.unipampa.lesse.canopus.Disk_IO_Counter#getCriteria()
   * @see #getDisk_IO_Counter()
   * @generated
   */
  EReference getDisk_IO_Counter_Criteria();

  /**
   * Returns the meta object for class '{@link org.unipampa.lesse.canopus.Criteria <em>Criteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Criteria</em>'.
   * @see org.unipampa.lesse.canopus.Criteria
   * @generated
   */
  EClass getCriteria();

  /**
   * Returns the meta object for the attribute '{@link org.unipampa.lesse.canopus.Criteria#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.unipampa.lesse.canopus.Criteria#getValue()
   * @see #getCriteria()
   * @generated
   */
  EAttribute getCriteria_Value();

  /**
   * Returns the meta object for the reference '{@link org.unipampa.lesse.canopus.Criteria#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Threshold</em>'.
   * @see org.unipampa.lesse.canopus.Criteria#getThreshold()
   * @see #getCriteria()
   * @generated
   */
  EReference getCriteria_Threshold();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.canopus.Hardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Hardware</em>'.
   * @see org.unipampa.lesse.canopus.Hardware
   * @generated
   */
  EEnum getHardware();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.canopus.SUTType <em>SUT Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SUT Type</em>'.
   * @see org.unipampa.lesse.canopus.SUTType
   * @generated
   */
  EEnum getSUTType();

  /**
   * Returns the meta object for enum '{@link org.unipampa.lesse.canopus.COUNTER_DISK <em>COUNTER DISK</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>COUNTER DISK</em>'.
   * @see org.unipampa.lesse.canopus.COUNTER_DISK
   * @generated
   */
  EEnum getCOUNTER_DISK();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CanopusFactory getCanopusFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.ModelImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Includes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INCLUDES = eINSTANCE.getModel_Includes();

    /**
     * The meta object literal for the '<em><b>Monitorings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MONITORINGS = eINSTANCE.getModel_Monitorings();

    /**
     * The meta object literal for the '<em><b>Suts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SUTS = eINSTANCE.getModel_Suts();

    /**
     * The meta object literal for the '<em><b>Load Generators</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__LOAD_GENERATORS = eINSTANCE.getModel_LoadGenerators();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.IncludeImpl <em>Include</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.IncludeImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getInclude()
     * @generated
     */
    EClass INCLUDE = eINSTANCE.getInclude();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUDE__IMPORT_URI = eINSTANCE.getInclude_ImportURI();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCLUDE__NAME = eINSTANCE.getInclude_Name();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.MonitoringImpl <em>Monitoring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.MonitoringImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMonitoring()
     * @generated
     */
    EClass MONITORING = eINSTANCE.getMonitoring();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITORING__NAME = eINSTANCE.getMonitoring_Name();

    /**
     * The meta object literal for the '<em><b>Project Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITORING__PROJECT_LABEL = eINSTANCE.getMonitoring_ProjectLabel();

    /**
     * The meta object literal for the '<em><b>Project Author</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITORING__PROJECT_AUTHOR = eINSTANCE.getMonitoring_ProjectAuthor();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITORING__DESCRIPTION = eINSTANCE.getMonitoring_Description();

    /**
     * The meta object literal for the '<em><b>Suts</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONITORING__SUTS = eINSTANCE.getMonitoring_Suts();

    /**
     * The meta object literal for the '<em><b>Load Generators</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONITORING__LOAD_GENERATORS = eINSTANCE.getMonitoring_LoadGenerators();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.MetricImpl <em>Metric</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.MetricImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMetric()
     * @generated
     */
    EClass METRIC = eINSTANCE.getMetric();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC__NAME = eINSTANCE.getMetric_Name();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METRIC__THRESHOLD = eINSTANCE.getMetric_Threshold();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.SUTImpl <em>SUT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.SUTImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getSUT()
     * @generated
     */
    EClass SUT = eINSTANCE.getSUT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUT__NAME = eINSTANCE.getSUT_Name();

    /**
     * The meta object literal for the '<em><b>Hostname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUT__HOSTNAME = eINSTANCE.getSUT_Hostname();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUT__IP = eINSTANCE.getSUT_Ip();

    /**
     * The meta object literal for the '<em><b>Hardware</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUT__HARDWARE = eINSTANCE.getSUT_Hardware();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUT__TYPE = eINSTANCE.getSUT_Type();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.LoadGeneratorImpl <em>Load Generator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.LoadGeneratorImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getLoadGenerator()
     * @generated
     */
    EClass LOAD_GENERATOR = eINSTANCE.getLoadGenerator();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_GENERATOR__NAME = eINSTANCE.getLoadGenerator_Name();

    /**
     * The meta object literal for the '<em><b>Hostname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_GENERATOR__HOSTNAME = eINSTANCE.getLoadGenerator_Hostname();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_GENERATOR__IP = eINSTANCE.getLoadGenerator_Ip();

    /**
     * The meta object literal for the '<em><b>Hardware</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_GENERATOR__HARDWARE = eINSTANCE.getLoadGenerator_Hardware();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.MonitorImpl <em>Monitor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.MonitorImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMonitor()
     * @generated
     */
    EClass MONITOR = eINSTANCE.getMonitor();

    /**
     * The meta object literal for the '<em><b>Hostname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITOR__HOSTNAME = eINSTANCE.getMonitor_Hostname();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITOR__IP = eINSTANCE.getMonitor_Ip();

    /**
     * The meta object literal for the '<em><b>Hardware</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MONITOR__HARDWARE = eINSTANCE.getMonitor_Hardware();

    /**
     * The meta object literal for the '<em><b>Sut</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONITOR__SUT = eINSTANCE.getMonitor_Sut();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.MetricModelImpl <em>Metric Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.MetricModelImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMetricModel()
     * @generated
     */
    EClass METRIC_MODEL = eINSTANCE.getMetricModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC_MODEL__NAME = eINSTANCE.getMetricModel_Name();

    /**
     * The meta object literal for the '<em><b>Metricmodel</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METRIC_MODEL__METRICMODEL = eINSTANCE.getMetricModel_Metricmodel();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.MetricCollectionImpl <em>Metric Collection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.MetricCollectionImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMetricCollection()
     * @generated
     */
    EClass METRIC_COLLECTION = eINSTANCE.getMetricCollection();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METRIC_COLLECTION__METRIC = eINSTANCE.getMetricCollection_Metric();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.ThresholdImpl <em>Threshold</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.ThresholdImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getThreshold()
     * @generated
     */
    EClass THRESHOLD = eINSTANCE.getThreshold();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute THRESHOLD__VALUE = eINSTANCE.getThreshold_Value();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.MemoryImpl <em>Memory</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.MemoryImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getMemory()
     * @generated
     */
    EClass MEMORY = eINSTANCE.getMemory();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.DiskImpl <em>Disk</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.DiskImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getDisk()
     * @generated
     */
    EClass DISK = eINSTANCE.getDisk();

    /**
     * The meta object literal for the '<em><b>Disk io counter</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISK__DISK_IO_COUNTER = eINSTANCE.getDisk_Disk_io_counter();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.TransactionImpl <em>Transaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.TransactionImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getTransaction()
     * @generated
     */
    EClass TRANSACTION = eINSTANCE.getTransaction();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.Disk_IO_CounterImpl <em>Disk IO Counter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.Disk_IO_CounterImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getDisk_IO_Counter()
     * @generated
     */
    EClass DISK_IO_COUNTER = eINSTANCE.getDisk_IO_Counter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISK_IO_COUNTER__NAME = eINSTANCE.getDisk_IO_Counter_Name();

    /**
     * The meta object literal for the '<em><b>Counter Disk</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISK_IO_COUNTER__COUNTER_DISK = eINSTANCE.getDisk_IO_Counter_CounterDisk();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISK_IO_COUNTER__THRESHOLD = eINSTANCE.getDisk_IO_Counter_Threshold();

    /**
     * The meta object literal for the '<em><b>Criteria</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISK_IO_COUNTER__CRITERIA = eINSTANCE.getDisk_IO_Counter_Criteria();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.impl.CriteriaImpl <em>Criteria</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.impl.CriteriaImpl
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getCriteria()
     * @generated
     */
    EClass CRITERIA = eINSTANCE.getCriteria();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CRITERIA__VALUE = eINSTANCE.getCriteria_Value();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CRITERIA__THRESHOLD = eINSTANCE.getCriteria_Threshold();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.Hardware <em>Hardware</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.Hardware
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getHardware()
     * @generated
     */
    EEnum HARDWARE = eINSTANCE.getHardware();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.SUTType <em>SUT Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.SUTType
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getSUTType()
     * @generated
     */
    EEnum SUT_TYPE = eINSTANCE.getSUTType();

    /**
     * The meta object literal for the '{@link org.unipampa.lesse.canopus.COUNTER_DISK <em>COUNTER DISK</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.unipampa.lesse.canopus.COUNTER_DISK
     * @see org.unipampa.lesse.canopus.impl.CanopusPackageImpl#getCOUNTER_DISK()
     * @generated
     */
    EEnum COUNTER_DISK = eINSTANCE.getCOUNTER_DISK();

  }

} //CanopusPackage
