/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Disk IO Counter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getName <em>Name</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getCounterDisk <em>Counter Disk</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getThreshold <em>Threshold</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getCriteria <em>Criteria</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.canopus.CanopusPackage#getDisk_IO_Counter()
 * @model
 * @generated
 */
public interface Disk_IO_Counter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getDisk_IO_Counter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Counter Disk</b></em>' attribute list.
   * The list contents are of type {@link org.unipampa.lesse.canopus.COUNTER_DISK}.
   * The literals are from the enumeration {@link org.unipampa.lesse.canopus.COUNTER_DISK}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Counter Disk</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Counter Disk</em>' attribute list.
   * @see org.unipampa.lesse.canopus.COUNTER_DISK
   * @see org.unipampa.lesse.canopus.CanopusPackage#getDisk_IO_Counter_CounterDisk()
   * @model unique="false"
   * @generated
   */
  EList<COUNTER_DISK> getCounterDisk();

  /**
   * Returns the value of the '<em><b>Threshold</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Threshold</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold</em>' reference.
   * @see #setThreshold(Threshold)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getDisk_IO_Counter_Threshold()
   * @model
   * @generated
   */
  Threshold getThreshold();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getThreshold <em>Threshold</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Threshold</em>' reference.
   * @see #getThreshold()
   * @generated
   */
  void setThreshold(Threshold value);

  /**
   * Returns the value of the '<em><b>Criteria</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Criteria</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Criteria</em>' reference.
   * @see #setCriteria(Criteria)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getDisk_IO_Counter_Criteria()
   * @model
   * @generated
   */
  Criteria getCriteria();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Disk_IO_Counter#getCriteria <em>Criteria</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Criteria</em>' reference.
   * @see #getCriteria()
   * @generated
   */
  void setCriteria(Criteria value);

} // Disk_IO_Counter
