/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Memory</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unipampa.lesse.canopus.CanopusPackage#getMemory()
 * @model
 * @generated
 */
public interface Memory extends Metric
{
} // Memory
