/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monitoring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.canopus.Monitoring#getName <em>Name</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitoring#getProjectLabel <em>Project Label</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitoring#getProjectAuthor <em>Project Author</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitoring#getDescription <em>Description</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitoring#getSuts <em>Suts</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitoring#getLoadGenerators <em>Load Generators</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring()
 * @model
 * @generated
 */
public interface Monitoring extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitoring#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Project Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project Label</em>' attribute.
   * @see #setProjectLabel(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring_ProjectLabel()
   * @model
   * @generated
   */
  String getProjectLabel();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitoring#getProjectLabel <em>Project Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project Label</em>' attribute.
   * @see #getProjectLabel()
   * @generated
   */
  void setProjectLabel(String value);

  /**
   * Returns the value of the '<em><b>Project Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project Author</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project Author</em>' attribute.
   * @see #setProjectAuthor(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring_ProjectAuthor()
   * @model
   * @generated
   */
  String getProjectAuthor();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitoring#getProjectAuthor <em>Project Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project Author</em>' attribute.
   * @see #getProjectAuthor()
   * @generated
   */
  void setProjectAuthor(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitoring#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Suts</b></em>' reference list.
   * The list contents are of type {@link org.unipampa.lesse.canopus.SUT}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Suts</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suts</em>' reference list.
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring_Suts()
   * @model
   * @generated
   */
  EList<SUT> getSuts();

  /**
   * Returns the value of the '<em><b>Load Generators</b></em>' reference list.
   * The list contents are of type {@link org.unipampa.lesse.canopus.LoadGenerator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Load Generators</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Load Generators</em>' reference list.
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitoring_LoadGenerators()
   * @model
   * @generated
   */
  EList<LoadGenerator> getLoadGenerators();

} // Monitoring
