/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Monitor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.unipampa.lesse.canopus.Monitor#getHostname <em>Hostname</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitor#getIp <em>Ip</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitor#getHardware <em>Hardware</em>}</li>
 *   <li>{@link org.unipampa.lesse.canopus.Monitor#getSut <em>Sut</em>}</li>
 * </ul>
 *
 * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitor()
 * @model
 * @generated
 */
public interface Monitor extends EObject
{
  /**
   * Returns the value of the '<em><b>Hostname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hostname</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hostname</em>' attribute.
   * @see #setHostname(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitor_Hostname()
   * @model
   * @generated
   */
  String getHostname();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitor#getHostname <em>Hostname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hostname</em>' attribute.
   * @see #getHostname()
   * @generated
   */
  void setHostname(String value);

  /**
   * Returns the value of the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ip</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' attribute.
   * @see #setIp(String)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitor_Ip()
   * @model
   * @generated
   */
  String getIp();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitor#getIp <em>Ip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' attribute.
   * @see #getIp()
   * @generated
   */
  void setIp(String value);

  /**
   * Returns the value of the '<em><b>Hardware</b></em>' attribute.
   * The literals are from the enumeration {@link org.unipampa.lesse.canopus.Hardware}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hardware</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hardware</em>' attribute.
   * @see org.unipampa.lesse.canopus.Hardware
   * @see #setHardware(Hardware)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitor_Hardware()
   * @model
   * @generated
   */
  Hardware getHardware();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitor#getHardware <em>Hardware</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hardware</em>' attribute.
   * @see org.unipampa.lesse.canopus.Hardware
   * @see #getHardware()
   * @generated
   */
  void setHardware(Hardware value);

  /**
   * Returns the value of the '<em><b>Sut</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sut</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sut</em>' reference.
   * @see #setSut(SUT)
   * @see org.unipampa.lesse.canopus.CanopusPackage#getMonitor_Sut()
   * @model
   * @generated
   */
  SUT getSut();

  /**
   * Sets the value of the '{@link org.unipampa.lesse.canopus.Monitor#getSut <em>Sut</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sut</em>' reference.
   * @see #getSut()
   * @generated
   */
  void setSut(SUT value);

} // Monitor
