/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>SUT Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.unipampa.lesse.canopus.CanopusPackage#getSUTType()
 * @model
 * @generated
 */
public enum SUTType implements Enumerator
{
  /**
   * The '<em><b>DESKTOPAPP</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DESKTOPAPP_VALUE
   * @generated
   * @ordered
   */
  DESKTOPAPP(0, "DESKTOPAPP", "DESKTOPAPP"),

  /**
   * The '<em><b>DATABASE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATABASE_VALUE
   * @generated
   * @ordered
   */
  DATABASE(1, "DATABASE", "DATABASE"),

  /**
   * The '<em><b>WEBAPP</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEBAPP_VALUE
   * @generated
   * @ordered
   */
  WEBAPP(2, "WEBAPP", "WEBAPP"),

  /**
   * The '<em><b>WEBSERVICE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEBSERVICE_VALUE
   * @generated
   * @ordered
   */
  WEBSERVICE(3, "WEBSERVICE", "WEBSERVICE");

  /**
   * The '<em><b>DESKTOPAPP</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DESKTOPAPP</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DESKTOPAPP
   * @model
   * @generated
   * @ordered
   */
  public static final int DESKTOPAPP_VALUE = 0;

  /**
   * The '<em><b>DATABASE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>DATABASE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATABASE
   * @model
   * @generated
   * @ordered
   */
  public static final int DATABASE_VALUE = 1;

  /**
   * The '<em><b>WEBAPP</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEBAPP</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEBAPP
   * @model
   * @generated
   * @ordered
   */
  public static final int WEBAPP_VALUE = 2;

  /**
   * The '<em><b>WEBSERVICE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>WEBSERVICE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #WEBSERVICE
   * @model
   * @generated
   * @ordered
   */
  public static final int WEBSERVICE_VALUE = 3;

  /**
   * An array of all the '<em><b>SUT Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SUTType[] VALUES_ARRAY =
    new SUTType[]
    {
      DESKTOPAPP,
      DATABASE,
      WEBAPP,
      WEBSERVICE,
    };

  /**
   * A public read-only list of all the '<em><b>SUT Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SUTType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>SUT Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUTType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SUTType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SUT Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUTType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SUTType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SUT Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SUTType get(int value)
  {
    switch (value)
    {
      case DESKTOPAPP_VALUE: return DESKTOPAPP;
      case DATABASE_VALUE: return DATABASE;
      case WEBAPP_VALUE: return WEBAPP;
      case WEBSERVICE_VALUE: return WEBSERVICE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SUTType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SUTType
