/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.canopus;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transaction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.unipampa.lesse.canopus.CanopusPackage#getTransaction()
 * @model
 * @generated
 */
public interface Transaction extends Metric
{
} // Transaction
