/*
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CanopusUiModule extends AbstractCanopusUiModule {
}
