/*
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CanopusStandaloneSetup extends CanopusStandaloneSetupGenerated {

	def static void doSetup() {
		new CanopusStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
