/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse;

import org.unipampa.lesse.CanopusStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CanopusStandaloneSetup extends CanopusStandaloneSetupGenerated {
  public static void doSetup() {
    new CanopusStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
