/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse;

import org.unipampa.lesse.AbstractCanopusRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CanopusRuntimeModule extends AbstractCanopusRuntimeModule {
}
