/**
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.validation;

import org.unipampa.lesse.validation.AbstractCanopusValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CanopusValidator extends AbstractCanopusValidator {
}
