/*
 * generated by Xtext 2.14.0
 */
package org.unipampa.lesse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCanopusScopeProvider extends DelegatingScopeProvider {
}
